name: deploy-trymudblazor

on:
  workflow_dispatch:

jobs:
  deploy-web-app:
    name: Deploy web app to try.mudblazor.com
    if: ${{ github.repository_owner == 'MudBlazor' }}
    uses: MudBlazor/Workflows/.github/workflows/template-deploy-web-app.yml@main
    with:
      web-app-name: trymudblazor
      web-app-slot-name:  'staging'
      swap-slots: true
      project-directory: './src/TryMudBlazor.Server'
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR }}
      azure-cred: ${{ secrets.AZURE_CREDENTIALS_TRY_PROD }}